#!/bin/bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
if [[ $USER != root ]]; then
	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
	exit 1
fi
trap "rm -f /run/$0.pid; exit" INT TERM EXIT
echo "$BASHPID" > /run/$0.pid





apt-get -y install dnsmasq nfs-kernel-server tftpd-hpa
mkdir -p /var/lib/tftpboot

echo "dhcp-range=192.168.1.223,192.168.1.254,12h" >> /etc/dnsmasq.conf
echo "dhcp-no-override" >> /etc/dnsmasq.conf
echo "dhcp-boot=pxelinux.0" >> /etc/dnsmasq.conf
echo "enable-tftp" >> /etc/dnsmasq.conf
echo "tftp-root=/var/lib/tftpboot" >> /etc/dnsmasq.conf

systemctl restart dnsmasq.service






rm -f /run/$0.pid
trap - INT TERM EXIT
exit 0
